### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by aamandafelix** [fga-gpp-mds/2018.1-Grupo2#10]
### Descrição
Elaborar Roadmap

### Critérios de Aceitação
- [x] Roadmap revisado por todos da equipe de EPS

### Tarefas
- [x] Roadmap de projeto @daluzguilherme 
- [x] Roadmap de arquitetura @lucasca73 @MiguelNery 
- [x] Roadmap de DevOps @amandabezerra @marlonbymendes

**Comment by daluzguilherme** [comment]
Pessoal, quem tiver ao menos uma primeira versão do roadmap por favor comite. Depois fazemos revisão/refatoração. @amandabezerra , @MiguelNery , @marlonbymendes , @lucasca73

**Comment by aamandafelix** [comment]
Roadmap de DevOps já está disponível na branch docs.
PR #83

**Comment by daluzguilherme** [comment]
@lucasca73 e @MiguelNery vcs ja têm roadmap de arquitetura? Não vi na branch docs. Pq os checklists estão marcados?
